const { Job } = require('./models');

const sampleJobs = [
  {
    title: 'Full Stack Developer',
    company: 'Tech Solutions Inc',
    location: 'Bangalore, India',
    salaryMin: 800000,
    salaryMax: 1500000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 5,
    description: 'We are looking for a talented Full Stack Developer to join our team. You will work on cutting-edge web applications using modern technologies.',
    requirements: [
      '2+ years of experience in web development',
      'Strong knowledge of React and Node.js',
      'Experience with databases (SQL/NoSQL)',
      'Good understanding of RESTful APIs',
      'Excellent problem-solving skills'
    ],
    skills: ['React', 'Node.js', 'JavaScript', 'TypeScript', 'MongoDB', 'Express', 'Git'],
    jobType: 'Full-time',
    source: 'Company',
    sourceUrl: 'https://example.com/jobs/1',
    isActive: true,
  },
  {
    title: 'Frontend Developer',
    company: 'Digital Innovations',
    location: 'Mumbai, India',
    salaryMin: 600000,
    salaryMax: 1200000,
    salaryCurrency: 'INR',
    experienceMin: 1,
    experienceMax: 3,
    description: 'Join our frontend team to build beautiful and responsive user interfaces.',
    requirements: [
      'Experience with React or Vue.js',
      'Strong CSS and HTML skills',
      'Understanding of responsive design',
      'Knowledge of modern build tools'
    ],
    skills: ['React', 'JavaScript', 'CSS', 'HTML', 'Tailwind CSS', 'Webpack'],
    jobType: 'Full-time',
    source: 'LinkedIn',
    isActive: true,
  },
  {
    title: 'Backend Developer',
    company: 'Cloud Systems Ltd',
    location: 'Hyderabad, India',
    salaryMin: 700000,
    salaryMax: 1400000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 4,
    description: 'Build scalable backend systems and APIs for our cloud platform.',
    requirements: [
      'Strong experience with Node.js or Python',
      'Database design and optimization',
      'RESTful API development',
      'Cloud platform experience (AWS/Azure)'
    ],
    skills: ['Node.js', 'Python', 'PostgreSQL', 'AWS', 'Docker', 'Microservices'],
    jobType: 'Full-time',
    source: 'Naukri',
    isActive: true,
  },
  {
    title: 'Data Analyst',
    company: 'Analytics Pro',
    location: 'Pune, India',
    salaryMin: 500000,
    salaryMax: 900000,
    salaryCurrency: 'INR',
    experienceMin: 1,
    experienceMax: 3,
    description: 'Analyze data and provide insights to drive business decisions.',
    requirements: [
      'Strong analytical skills',
      'Experience with SQL and Excel',
      'Data visualization tools (Tableau/Power BI)',
      'Statistical analysis knowledge'
    ],
    skills: ['SQL', 'Python', 'Excel', 'Tableau', 'Statistics', 'Data Visualization'],
    jobType: 'Full-time',
    source: 'Indeed',
    isActive: true,
  },
  {
    title: 'DevOps Engineer',
    company: 'Infrastructure Masters',
    location: 'Delhi, India',
    salaryMin: 900000,
    salaryMax: 1800000,
    salaryCurrency: 'INR',
    experienceMin: 3,
    experienceMax: 6,
    description: 'Manage and automate our infrastructure and deployment pipelines.',
    requirements: [
      'Experience with CI/CD pipelines',
      'Strong Linux/Unix knowledge',
      'Container orchestration (Kubernetes)',
      'Infrastructure as Code (Terraform)'
    ],
    skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform', 'Linux', 'Python'],
    jobType: 'Full-time',
    source: 'Company',
    isActive: true,
  },
  {
    title: 'UI/UX Designer',
    company: 'Creative Studios',
    location: 'Bangalore, India',
    salaryMin: 600000,
    salaryMax: 1100000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 4,
    description: 'Design intuitive and beautiful user experiences for web and mobile applications.',
    requirements: [
      'Strong portfolio showcasing UI/UX work',
      'Proficiency in Figma or Adobe XD',
      'Understanding of user-centered design',
      'Experience with design systems'
    ],
    skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research', 'Wireframing'],
    jobType: 'Full-time',
    source: 'LinkedIn',
    isActive: true,
  },
  {
    title: 'Machine Learning Engineer',
    company: 'AI Innovations',
    location: 'Bangalore, India',
    salaryMin: 1200000,
    salaryMax: 2500000,
    salaryCurrency: 'INR',
    experienceMin: 3,
    experienceMax: 6,
    description: 'Build and deploy machine learning models to solve complex business problems.',
    requirements: [
      'Strong Python programming skills',
      'Experience with ML frameworks (TensorFlow/PyTorch)',
      'Understanding of ML algorithms and statistics',
      'Experience with model deployment'
    ],
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Deep Learning', 'NLP', 'Computer Vision'],
    jobType: 'Full-time',
    source: 'Company',
    isActive: true,
  },
  {
    title: 'Mobile App Developer',
    company: 'Mobile First Tech',
    location: 'Gurgaon, India',
    salaryMin: 700000,
    salaryMax: 1400000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 5,
    description: 'Develop native and cross-platform mobile applications for iOS and Android.',
    requirements: [
      'Experience with React Native or Flutter',
      'Knowledge of mobile app architecture',
      'Understanding of mobile UI/UX principles',
      'Experience with app store deployment'
    ],
    skills: ['React Native', 'Flutter', 'JavaScript', 'Dart', 'iOS', 'Android', 'Firebase'],
    jobType: 'Full-time',
    source: 'Naukri',
    isActive: true,
  },
  {
    title: 'QA Engineer',
    company: 'Quality Assurance Corp',
    location: 'Chennai, India',
    salaryMin: 500000,
    salaryMax: 1000000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 4,
    description: 'Ensure software quality through manual and automated testing.',
    requirements: [
      'Experience with test automation frameworks',
      'Strong understanding of testing methodologies',
      'API testing experience',
      'Bug tracking and reporting'
    ],
    skills: ['Selenium', 'Jest', 'Cypress', 'API Testing', 'Manual Testing', 'JIRA', 'Test Automation'],
    jobType: 'Full-time',
    source: 'Indeed',
    isActive: true,
  },
  {
    title: 'Product Manager',
    company: 'Product Innovations',
    location: 'Mumbai, India',
    salaryMin: 1500000,
    salaryMax: 3000000,
    salaryCurrency: 'INR',
    experienceMin: 4,
    experienceMax: 8,
    description: 'Lead product strategy and roadmap for our flagship products.',
    requirements: [
      'Strong product management experience',
      'Excellent communication skills',
      'Data-driven decision making',
      'Experience with agile methodologies'
    ],
    skills: ['Product Strategy', 'Agile', 'User Stories', 'Analytics', 'Roadmapping', 'Stakeholder Management'],
    jobType: 'Full-time',
    source: 'LinkedIn',
    isActive: true,
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'SecureNet Solutions',
    location: 'Pune, India',
    salaryMin: 800000,
    salaryMax: 1600000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 5,
    description: 'Monitor and protect our systems from security threats and vulnerabilities.',
    requirements: [
      'Knowledge of security frameworks and standards',
      'Experience with security tools and SIEM',
      'Understanding of network security',
      'Incident response experience'
    ],
    skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Firewall', 'Vulnerability Assessment', 'Compliance'],
    jobType: 'Full-time',
    source: 'Company',
    isActive: true,
  },
  {
    title: 'Cloud Architect',
    company: 'Cloud Solutions Inc',
    location: 'Hyderabad, India',
    salaryMin: 1800000,
    salaryMax: 3500000,
    salaryCurrency: 'INR',
    experienceMin: 5,
    experienceMax: 10,
    description: 'Design and implement scalable cloud infrastructure solutions.',
    requirements: [
      'Expert knowledge of AWS/Azure/GCP',
      'Cloud architecture design patterns',
      'Cost optimization strategies',
      'Security and compliance expertise'
    ],
    skills: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'Serverless', 'Microservices', 'Terraform'],
    jobType: 'Full-time',
    source: 'LinkedIn',
    isActive: true,
  },
  {
    title: 'Business Analyst',
    company: 'Business Intelligence Ltd',
    location: 'Bangalore, India',
    salaryMin: 600000,
    salaryMax: 1200000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 5,
    description: 'Bridge the gap between business needs and technical solutions.',
    requirements: [
      'Strong analytical and problem-solving skills',
      'Experience with requirements gathering',
      'Knowledge of business process modeling',
      'Excellent documentation skills'
    ],
    skills: ['Requirements Analysis', 'SQL', 'Excel', 'JIRA', 'Business Process Modeling', 'Stakeholder Management'],
    jobType: 'Full-time',
    source: 'Naukri',
    isActive: true,
  },
  {
    title: 'Blockchain Developer',
    company: 'Crypto Innovations',
    location: 'Remote',
    salaryMin: 1000000,
    salaryMax: 2200000,
    salaryCurrency: 'INR',
    experienceMin: 2,
    experienceMax: 5,
    description: 'Develop decentralized applications and smart contracts on blockchain platforms.',
    requirements: [
      'Experience with Solidity and Ethereum',
      'Understanding of blockchain fundamentals',
      'Smart contract development',
      'Web3.js or Ethers.js experience'
    ],
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'Smart Contracts', 'Blockchain', 'JavaScript', 'Cryptography'],
    jobType: 'Full-time',
    source: 'Company',
    isActive: true,
  },
  {
    title: 'Technical Writer',
    company: 'Documentation Experts',
    location: 'Pune, India',
    salaryMin: 400000,
    salaryMax: 800000,
    salaryCurrency: 'INR',
    experienceMin: 1,
    experienceMax: 3,
    description: 'Create clear and comprehensive technical documentation for our products.',
    requirements: [
      'Excellent writing and communication skills',
      'Ability to understand technical concepts',
      'Experience with documentation tools',
      'Attention to detail'
    ],
    skills: ['Technical Writing', 'Documentation', 'Markdown', 'API Documentation', 'Content Management', 'Git'],
    jobType: 'Full-time',
    source: 'Indeed',
    isActive: true,
  },
  {
    title: 'Site Reliability Engineer',
    company: 'Reliable Systems Inc',
    location: 'Bangalore, India',
    salaryMin: 1000000,
    salaryMax: 2000000,
    salaryCurrency: 'INR',
    experienceMin: 3,
    experienceMax: 6,
    description: 'Ensure high availability and reliability of production systems.',
    requirements: [
      'Strong Linux and networking knowledge',
      'Experience with monitoring and alerting',
      'Automation and scripting skills',
      'Incident management experience'
    ],
    skills: ['Linux', 'Kubernetes', 'Prometheus', 'Grafana', 'Python', 'Bash', 'Monitoring', 'Automation'],
    jobType: 'Full-time',
    source: 'LinkedIn',
    isActive: true,
  },
];

async function seedJobs() {
  try {
    console.log('Seeding sample jobs...');
    await Job.bulkCreate(sampleJobs);
    console.log('✓ Sample jobs created successfully!');
  } catch (error) {
    console.error('Error seeding jobs:', error);
  }
}

module.exports = { seedJobs };
